### register user 


POST http://127.0.0.1:5000/auth/login
Content-Type: application/json

{
  "email": "moabasshirahsan07@gmail.com",
  "password": "74587458"
  
}

### admins portal 

DELETE http://127.0.0.1:5000/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc3OTI3MzY2MywianRpIjoiMGNmOGYzZTQtMjJhMy00OWVhLWI0MzctMDJjMjg2OTVmNWU1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3NzkyNzM2NjMsImNzcmYiOiI4ZjVmMDBhNC04ODRmLTQ3ZjEtYmRlMy0yM2QxOTM2MzYzYTYiLCJleHAiOjE3NzkyNzQ1NjMsInJvbGUiOiJhZG1pbiJ9.jv5F_08HrIEaBk-7Iw_AbuTczg5mvNebfTHRVcCC_Vs


### login

POST http://127.0.0.1:5000/auth/register
Content-Type: application/json

{
  "email": "moabasshirahsan07@gmail.com",
  "password": "74587458"
  
}