"""empty message

Revision ID: a65bf074da57
Revises: a2f95491b5fc
Create Date: 2026-05-18 20:32:46.007220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65bf074da57'
down_revision = 'a2f95491b5fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('users')]

    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'role' not in columns:
            batch_op.add_column(sa.Column('role', sa.String(), nullable=True))
        if 'password_hash' in columns:
            batch_op.alter_column('password_hash',
                   existing_type=sa.TEXT(),
                   nullable=True,
                   existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
